### ISSUE TITLE
error running (kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError))

### ISSUE THREAD

**Issue by jpage4500** [joshfng/slack-keep-presence#1]
I'm trying this after learning of this issue: https://github.com/eskerda/slack-keep-presence/issues/12

I have SLACK_TOKEN defined but seeing the error below:

I'm guessing maybe this is an issue on my end? Maybe not the correct version of ruby installed Anyway, just wanted to ask while I try to figure out what's happening.

```
~/Downloads$ slack-keep-presence
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/slack-keep-presence-0.1.5/bin/slack-keep-presence:3:in `<top (required)>'
	from /usr/local/bin/slack-keep-presence:22:in `load'
	from /usr/local/bin/slack-keep-presence:22:in `<main>'
```

**Comment by jpage4500** [comment]
FWIW - I was able to fix this error.. I ended up updating ruby to the latest using homebrew using this command: https://stackoverflow.com/a/42286604/1777346
