### ISSUE TITLE
`require': cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by adammenges** [joshfng/slack-keep-presence#2]
```
|⇒  gem install slack-keep-presence
Successfully installed slack-keep-presence-0.1.7
1 gem installed

|⇒  slack-keep-presence
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/slack-keep-presence-0.1.7/bin/slack-keep-presence:3:in `<top (required)>'
	from /usr/local/bin/slack-keep-presence:22:in `load'
	from /usr/local/bin/slack-keep-presence:22:in `<main>'
```

**Comment by adammenges** [comment]
https://github.com/joshfng/slack-keep-presence/issues/1 didn't work for me, already on ruby 2.5

```
|⇒  ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
```

**Comment by adammenges** [comment]
ah, needed to reinstall after upgrading

might want to update the readme for folks :)
